config/routes.rb
Rails.application.routes.draw do
  resources :button_clicks

end

app/models/button_click.rb
class ButtonClick < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/button_clicks_controller.rb
class ButtonClicksController < ApplicationController
  before_action :set_button_click, only: [:show, :edit, :update, :destroy]

  # GET /button_clicks
  # GET /button_clicks.json
  def index
    @button_clicks = ButtonClick.all
  end

  # GET /button_clicks/1
  # GET /button_clicks/1.json
  def show
  end

  # GET /button_clicks/new
  def new
    @button_click = ButtonClick.new
  end

  # GET /button_clicks/1/edit
  def edit
  end

  # POST /button_clicks
  # POST /button_clicks.json
  def create
    @button_click = ButtonClick.new(button_click_params)

    respond_to do |format|
      if @button_click.save
        format.html { redirect_to :new_button_click, notice: 'Button click was successfully created.' }
        format.json { render :show, status: :created, location: @button_click }
      else
        format.html { render :new }
        format.json { render json: @button_click.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /button_clicks/1
  # PATCH/PUT /button_clicks/1.json
  def update
    respond_to do |format|
      if @button_click.update(button_click_params)
        format.html { redirect_to @button_click, notice: 'Button click was successfully updated.' }
        format.json { render :show, status: :ok, location: @button_click }
      else
        format.html { render :edit }
        format.json { render json: @button_click.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /button_clicks/1
  # DELETE /button_clicks/1.json
  def destroy
    @button_click.destroy
    respond_to do |format|
      format.html { redirect_to button_clicks_url, notice: 'Button click was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_button_click
      @button_click = ButtonClick.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def button_click_params
      params.fetch(:button_click, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/button_clicks_helper.rb
module ButtonClicksHelper
end

app/views/button_clicks/_form.html.erb
<%= form_for(@button_click) do |f| %>
  <% if @button_click.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@button_click.errors.count, "error") %> prohibited this button_click from being saved:</h2>

      <ul>
      <% @button_click.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit value: "Button has been clicked #{ButtonClick.count} times" %>
  </div>
<% end %>

app/views/button_clicks/edit.html.erb
<h1>Editing Button Click</h1>

<%= render 'form' %>

<%= link_to 'Show', @button_click %> |
<%= link_to 'Back', button_clicks_path %>

app/views/button_clicks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Button Clicks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @button_clicks.each do |button_click| %>
      <tr>
        <td><%= link_to 'Show', button_click %></td>
        <td><%= link_to 'Edit', edit_button_click_path(button_click) %></td>
        <td><%= link_to 'Destroy', button_click, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Button click', new_button_click_path %>

app/views/button_clicks/new.html.erb
<h1>New Button Click</h1>

<%= render 'form' %>

<%= link_to 'Back', button_clicks_path %>

app/views/button_clicks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_button_click_path(@button_click) %> |
<%= link_to 'Back', button_clicks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClickCounter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>